export const SERVICE = {
  USER_SERVICE: 'USER_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  CACHING_SERVICE: 'CACHING_SERVICE',
  MESSAGE_SERVICE: 'MESSAGE_SERVICE',
  FEED_SERVICE: 'FEED_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  MATCH_SERVICE: 'MATCH_SERVICE',
};
